name: Rust

on:
  push:
    branches:
      - 'main'
      - '!gh-pages'
  pull_request:

env:
  CARGO_BUILD_TARGET_DIR: ${{ github.workspace }}/target

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Rustup
        run: |
          rustup toolchain install nightly -c rustfmt
          rustup override set nightly
      - name: Rust toolchain info
        run: |
          rustc -Vv
          cargo -V
          rustup -V
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Cache CARGO_HOME
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get rustc commit hash
        id: cargo-target-cache
        run: |
          echo "::set-output name=rust_hash::$(rustc -Vv | grep commit-hash | awk '{print $2}')"
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-dir-${{ steps.cargo-target-cache.outputs.rust_hash }}-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo check --all
      - run: cargo build
      - run: cargo test
      - run: |
          cd interpreter
          cargo build
